# --------------------------------------------------------------------------- #
# Central S3 bucket: source code zip (for CodeBuild), the input Excel, the      #
# stored Dockerfile, and all run artifacts (queries.json, results, reports).    #
# --------------------------------------------------------------------------- #
resource "aws_s3_bucket" "main" {
  bucket        = local.bucket_name
  force_destroy = true # POC: allow `terraform destroy` to empty the bucket
  tags          = { Name = local.bucket_name }
}

resource "aws_s3_bucket_public_access_block" "main" {
  bucket                  = aws_s3_bucket.main.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "main" {
  bucket = aws_s3_bucket.main.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_versioning" "main" {
  bucket = aws_s3_bucket.main.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Build context (Dockerfile + buildspec + requirements + app/) zipped for CodeBuild.
data "archive_file" "source" {
  type        = "zip"
  source_dir  = "${path.module}/../src"
  output_path = "${path.module}/dist/source.zip"
  # Keep the zip deterministic: never include locally-generated bytecode.
  excludes = ["app/__pycache__", "**/__pycache__/**", "**/*.pyc"]
}

resource "aws_s3_object" "source_zip" {
  bucket      = aws_s3_bucket.main.id
  key         = "build/source.zip"
  source      = data.archive_file.source.output_path
  source_hash = data.archive_file.source.output_base64sha256
  tags        = { Name = "codebuild-source" }
}

# Requirement: store the initial Dockerfile in S3.
resource "aws_s3_object" "dockerfile" {
  bucket      = aws_s3_bucket.main.id
  key         = "docker/Dockerfile"
  source      = "${path.module}/../src/Dockerfile"
  source_hash = filemd5("${path.module}/../src/Dockerfile")
}

# The sample Excel workbook of 20 query pairs (generated by scripts/gen_excel.py).
resource "aws_s3_object" "queries_excel" {
  bucket      = aws_s3_bucket.main.id
  key         = "input/queries.xlsx"
  source      = "${path.module}/seed/queries.xlsx"
  source_hash = filemd5("${path.module}/seed/queries.xlsx")
}
